# Generated by Django 4.2.13 on 2024-07-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VapeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hits', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('multiplier', models.FloatField(default=0.0)),
                ('flavors', models.JSONField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
