# Generated by Django 4.2.13 on 2024-07-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humito_site', '0002_vapeimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vapeimages',
            name='vape_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humito_site.vapeinfo'),
        ),
    ]
