# Generated by Django 4.2.13 on 2024-07-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humito_site', '0003_alter_vapeimages_vape_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vapeinfo',
            name='hits',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='vapeinfo',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
