# Generated by Django 4.2.13 on 2024-07-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humito_site', '0004_alter_vapeinfo_hits_alter_vapeinfo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vapeinfo',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
