# Generated by Django 4.2.13 on 2024-07-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humito_site', '0005_vapeinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vapeinfo',
            name='flavors',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
