# Generated by Django 4.2.13 on 2024-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humito_site', '0006_alter_vapeinfo_flavors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vapeinfo',
            name='image',
            field=models.CharField(default=''),
        ),
    ]
